# generated by datamodel-codegen:
#   filename:  worker/active_targets.response.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class Telescope(BaseModel):
    id: int
    slug: str
    name: str
    timezone: Annotated[
        str | None, Field(description="IANA timezone (api_revision 1).")
    ] = None


class ProjectRef(BaseModel):
    id: int
    name: str
    priority: Annotated[
        int,
        Field(
            description="Effective Target Scheduler priority; the target's own priority breaks ties."
        ),
    ]
    ts_project_name: Annotated[
        str,
        Field(
            description='"#P<project_id> <project name>" (§4.4).', pattern="^#P\\d+ "
        ),
    ]


class OpticalTrainRef(BaseModel):
    key: Annotated[str, Field(description="Equals the Altair rig name.")]


class ExposurePlan(BaseModel):
    id: int
    filter: str
    exposure_seconds: Annotated[float, Field(gt=0.0)]
    desired_count: Annotated[int, Field(ge=0)]
    completed_count: Annotated[int, Field(ge=0)]
    remaining_count: Annotated[int, Field(ge=0)]
    schedule_count: Annotated[
        int | None,
        Field(
            description="What the worker writes as the Target Scheduler desired count (§4.3). Equals desired_count with completion basis 'acquired' (api_revision 1).",
            ge=0,
        ),
    ] = None


class ActiveTarget(BaseModel):
    id: int
    name: str
    ra_deg: Annotated[float, Field(ge=0.0, lt=360.0)]
    dec_deg: Annotated[float, Field(ge=-90.0, le=90.0)]
    status: Literal["draft", "submitted", "active", "in_progress", "completed", "cancelled"]
    priority: int
    notes: str | None = None
    nina_name: Annotated[
        str | None,
        Field(
            description='"#<target_id> <target name>" (§4.4, api_revision 1).',
            pattern="^#\\d+ ",
        ),
    ] = None
    rotation_deg: Annotated[
        float | None, Field(description="Sky position angle (api_revision 1).")
    ] = None
    min_altitude_deg: Annotated[float | None, Field(description="api_revision 1.")] = (
        None
    )
    project: ProjectRef | None = None
    optical_train: OpticalTrainRef | None = None
    exposure_plans: list[ExposurePlan]


class ActiveTargetsResponse(BaseModel):
    telescope: Telescope
    targets: list[ActiveTarget]
