# generated by datamodel-codegen:
#   filename:  worker/progress.response.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class Target(BaseModel):
    id: int
    status: Literal["draft", "submitted", "active", "in_progress", "completed", "cancelled"]
    percent_complete: Annotated[float, Field(ge=0.0, le=100.0)]


class ProgressResponse(BaseModel):
    ok: Literal[True]
    target: Target
