# generated by datamodel-codegen:
#   filename:  worker/progress.request.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class ExposurePlan(BaseModel):
    id: int
    completed_count: Annotated[int, Field(ge=0)]


class ProgressRequest(BaseModel):
    exposure_plans: list[ExposurePlan]
    status: Literal["draft", "submitted", "active", "in_progress", "completed", "cancelled"] | None = (
        None
    )
