# generated by datamodel-codegen:
#   filename:  worker/session_event.request.json

from __future__ import annotations

from datetime import date
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, Field


class SessionEventRequest(BaseModel):
    event: Literal["roof_open", "roof_close", "session_end"]
    at: Annotated[
        AwareDatetime, Field(description="ISO 8601 timestamp with a UTC offset.")
    ]
    night: Annotated[
        date,
        Field(
            description="Observing night: (date_obs in the telescope timezone - 12 h).date (§4.4)."
        ),
    ]
    target_ids: list[int] | None = None
