# generated by datamodel-codegen:
#   filename:  worker/target_event.request.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel


class TargetEventRequest(BaseModel):
    event_type: Literal["progress", "status_changed", "error", "frames_collected", "night_closed", "master_updated", "issue_opened", "issue_resolved", "session"]
    payload: dict[str, Any] | None = None
