# generated by datamodel-codegen:
#   filename:  worker/target_event.response.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class Event(BaseModel):
    id: int
    event_type: str


class TargetEventResponse(BaseModel):
    ok: Literal[True]
    event: Event
