# generated by datamodel-codegen:
#   filename:  worker/target_file.request.json

from __future__ import annotations

from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel


class TargetFileRequest(BaseModel):
    url: AnyUrl
    kind: Literal["sub", "stacked", "preview", "log"] | None = "sub"
    filter: str | None = None
    captured_at: AwareDatetime | None = None
