# generated by datamodel-codegen:
#   filename:  worker/target_file.response.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class File(BaseModel):
    id: int
    url: str | None
    kind: str


class TargetFileResponse(BaseModel):
    ok: Literal[True]
    file: File
