// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import AutoRefreshController from "./auto_refresh_controller"
application.register("auto-refresh", AutoRefreshController)

import LocalClockController from "./local_clock_controller"
application.register("local-clock", LocalClockController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HorizonPreviewController from "./horizon_preview_controller"
application.register("horizon-preview", HorizonPreviewController)

import RowLinkController from "./row_link_controller"
application.register("row-link", RowLinkController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)
