# generated by datamodel-codegen:
#   filename:  processing/calibration_master.request.json

from __future__ import annotations

from datetime import date
from typing import Annotated, Literal

from pydantic import BaseModel, Field


class CalibrationMasterRequest(BaseModel):
    optical_train: str
    kind: Literal["bias", "dark", "flat", "darkflat"]
    filter: str | None = None
    exposure_s: float | None = None
    gain: float | None = None
    offset: float | None = None
    binning: str | None = None
    sensor_temp_c: float | None = None
    rotator_pos: float | None = None
    night: date | None = None
    n_frames: Annotated[int, Field(ge=1)]
    sha256: Annotated[
        str,
        Field(
            description="Lower-case hex SHA-256 of a file's bytes. The natural key of a frame everywhere.",
            pattern="^[0-9a-f]{64}$",
        ),
    ]
    superseded: bool | None = False
