# generated by datamodel-codegen:
#   filename:  processing/command.json

from __future__ import annotations

from datetime import date
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel

from ..shared import common


class IssueWaivePayload(BaseModel):
    fingerprint: str
    note: str


class SetModePayload(BaseModel):
    target_id: int
    mode: Literal["master_merge", "frame_reintegration"]


class FetchDecisionPayload(BaseModel):
    fingerprint: str


class EquipmentEventPayload(BaseModel):
    equipment_event_id: int


class RefreshConfigPayload(RootModel[dict[str, Any]]):
    root: Annotated[dict[str, Any], Field(max_length=0)]


class Command(BaseModel):
    id: int
    kind: Literal["assign_frames", "rerun", "night_include", "night_exclude", "issue_waive", "rereference", "set_mode", "approve_fetch", "deny_fetch", "equipment_event", "refresh_config", "night_ready"]
    payload: dict[str, Any]
    created_at: Annotated[
        AwareDatetime, Field(description="ISO 8601 timestamp with a UTC offset.")
    ]


class FrameSelector(BaseModel):
    optical_train: str
    night: Annotated[
        date,
        Field(
            description="Observing night: (date_obs in the telescope timezone - 12 h).date (§4.4)."
        ),
    ]
    object: str | None = None


class AssignFramesPayload1(BaseModel):
    target_id: int
    sha256s: Annotated[list[common.Sha256], Field(min_length=1)]
    selector: FrameSelector | None = None


class AssignFramesPayload2(BaseModel):
    target_id: int
    sha256s: Annotated[list[common.Sha256] | None, Field(min_length=1)] = None
    selector: FrameSelector


class AssignFramesPayload(RootModel[AssignFramesPayload1 | AssignFramesPayload2]):
    root: AssignFramesPayload1 | AssignFramesPayload2


class RerunPayload(BaseModel):
    target_id: int | None = None
    night: Annotated[
        date | None,
        Field(
            description="Observing night: (date_obs in the telescope timezone - 12 h).date (§4.4)."
        ),
    ] = None
    filter: str | None = None
    issue_id: int | None = None


class NightSelectionPayload(BaseModel):
    target_id: int
    night: Annotated[
        date,
        Field(
            description="Observing night: (date_obs in the telescope timezone - 12 h).date (§4.4)."
        ),
    ]
    filter: str


class RereferencePayload(BaseModel):
    target_id: int
    from_night: Annotated[
        date | None,
        Field(
            description="Observing night: (date_obs in the telescope timezone - 12 h).date (§4.4)."
        ),
    ] = None


class NightReadyPayload(BaseModel):
    optical_train: str
    night: Annotated[
        date,
        Field(
            description="Observing night: (date_obs in the telescope timezone - 12 h).date (§4.4)."
        ),
    ]
    at: Annotated[
        AwareDatetime, Field(description="ISO 8601 timestamp with a UTC offset.")
    ]
    closed_by: Literal["session_end"]
