# generated by datamodel-codegen:
#   filename:  processing/command_ack.request.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel


class CommandAckRequest(BaseModel):
    state: Literal["succeeded", "failed"]
    result: dict[str, Any] | None = None
