# generated by datamodel-codegen:
#   filename:  processing/commands.response.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel

from . import command


class CommandsResponse(RootModel[list[command.Command]]):
    root: Annotated[
        list[command.Command],
        Field(
            description="GET /api/v1/processing/commands?state=pending (scope commands:read). Returned commands are marked delivered.",
            title="CommandsResponse",
        ),
    ]
