# generated by datamodel-codegen:
#   filename:  processing/config.response.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, Field

from ..shared import common


class Node(BaseModel):
    name: str


class Filter(BaseModel):
    name: Annotated[str, Field(description="Canonical filter name.")]
    aliases: Annotated[
        list[str] | None,
        Field(
            description="Raw FILTER header values that map onto this filter (case-insensitive)."
        ),
    ] = None
    bandpass_nm: float | None = None


class HeaderAliases(BaseModel):
    telescope: list[str] | None = None
    camera: list[str] | None = None


class OpticalTrain(BaseModel):
    key: Annotated[str, Field(description="Equals the Altair rig name.")]
    camera_type: Literal["mono", "osc"]
    bayer_pattern: str | None = None
    focal_length_mm: Annotated[float, Field(gt=0.0)]
    pixel_size_um: Annotated[float, Field(gt=0.0)]
    sensor_width_px: Annotated[int, Field(ge=1)]
    sensor_height_px: Annotated[int, Field(ge=1)]
    has_rotator: bool
    filters: list[Filter]
    header_aliases: HeaderAliases | None = None


class Telescope(BaseModel):
    slug: str
    timezone: Annotated[
        str,
        Field(
            description="IANA timezone; must equal Altair's site.timezone for the rig."
        ),
    ]
    latitude: Annotated[float, Field(ge=-90.0, le=90.0)]
    longitude: Annotated[float, Field(ge=-180.0, le=180.0)]
    elevation_m: float | None = None
    optical_trains: list[OpticalTrain]


class Target(BaseModel):
    id: int
    project_id: int
    telescope: Annotated[str, Field(description="Telescope slug.")]
    optical_train: Annotated[
        str | None,
        Field(description="Optical train key; null means any train of the telescope."),
    ] = None
    name: str
    nina_name: Annotated[str, Field(pattern="^#\\d+ ")]
    status: Literal["draft", "submitted", "active", "in_progress", "completed", "cancelled"]
    ra_deg: Annotated[float, Field(ge=0.0, lt=360.0)]
    dec_deg: Annotated[float, Field(ge=-90.0, le=90.0)]
    rotation_deg: float | None = None
    aliases: list[str]
    processing_settings: common.ProcessingSettings


class EquipmentEvent(BaseModel):
    id: int
    optical_train: str
    at: Annotated[
        AwareDatetime, Field(description="ISO 8601 timestamp with a UTC offset.")
    ]
    kind: Literal["sensor_cleaned", "filter_changed", "camera_rotated_manually", "reducer_changed", "collimated", "other"]
    filter: str | None = None
    note: str | None = None


class ProcessingConfigResponse(BaseModel):
    api_revision: Annotated[int, Field(ge=1)]
    node: Node
    telescopes: list[Telescope]
    targets: list[Target]
    equipment_events: list[EquipmentEvent]
