# generated by datamodel-codegen:
#   filename:  processing/data_product.metadata.json

from __future__ import annotations

from datetime import date
from typing import Annotated

from pydantic import BaseModel, Field

from ..shared import common


class Metrics(BaseModel):
    frames: Annotated[int | None, Field(ge=0)] = None
    rejected: Annotated[int | None, Field(ge=0)] = None
    total_exposure_s: Annotated[float | None, Field(ge=0.0)] = None
    fwhm: float | None = None
    eccentricity: float | None = None
    snr: float | None = None
    night_weights: dict[str, float] | None = None
    frame_sha256s: Annotated[
        list[common.Sha256] | None,
        Field(
            description="Lights used, so the Hub can compute usable/integrated counters."
        ),
    ] = None


class DataProductMetadata(BaseModel):
    target_id: int
    night: Annotated[
        date | None, Field(description="Set for night_master and provisional_noflat.")
    ] = None
    version: Annotated[
        int | None,
        Field(description="Set for multi_night_master and project_reference."),
    ] = None
    filter: str
    sha256: Annotated[
        str,
        Field(
            description="Lower-case hex SHA-256 of a file's bytes. The natural key of a frame everywhere.",
            pattern="^[0-9a-f]{64}$",
        ),
    ]
    size_bytes: Annotated[int, Field(ge=0)]
    archive_uri: Annotated[str | None, Field(pattern="^s3://")]
    nas_path: str | None = None
    metrics: Metrics | None = None
    supersedes_altair_id: int | None = None
