# generated by datamodel-codegen:
#   filename:  processing/frames_batch.request.json

from __future__ import annotations

from datetime import date
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, Field

from ..shared import common


class Frame(BaseModel):
    sha256: Annotated[
        str,
        Field(
            description="Lower-case hex SHA-256 of a file's bytes. The natural key of a frame everywhere.",
            pattern="^[0-9a-f]{64}$",
        ),
    ]
    altair_frame_id: int
    origin: Literal["collect", "import", "legacy_index"]
    telescope: Annotated[str, Field(description="Telescope slug.")]
    optical_train: Annotated[
        str, Field(description="Optical train key (= Altair rig).")
    ]
    target_id: int | None
    assignment_source: Annotated[
        Literal["header_token", "name", "coords", "manual", "unlinked"],
        Field(
            description="How a frame was linked to a Hub target (§8.2.3). A manual assignment is never overridden."
        ),
    ]
    image_type: Literal["light", "dark", "flat", "bias", "darkflat"]
    night: Annotated[
        date,
        Field(
            description="Observing night: (date_obs in the telescope timezone - 12 h).date (§4.4)."
        ),
    ]
    date_obs: Annotated[
        AwareDatetime, Field(description="ISO 8601 timestamp with a UTC offset.")
    ]
    object_header: str | None = None
    filter: Annotated[str | None, Field(description="Canonical filter name.")] = None
    exposure_s: float | None = None
    gain: float | None = None
    offset: float | None = None
    binning: Annotated[str | None, Field(pattern="^\\d+x\\d+$")] = None
    readout_mode: str | None = None
    sensor_temp_c: float | None = None
    rotator_pos: float | None = None
    rotator_units: str | None = None
    ra_deg: float | None = None
    dec_deg: float | None = None
    rotation_deg: float | None = None
    width_px: int | None = None
    height_px: int | None = None
    file_name: str
    logical_path: str
    status: Literal["collected", "valid", "invalid", "held", "processed", "rejected"]
    status_reason: str | None = None
    quality: common.FrameQuality | None = None
    storage: common.FrameStorage | None = None
    headers: Annotated[
        dict[str, Any] | None,
        Field(description="Full or summary FITS/XISF headers (hub.frame_headers)."),
    ] = None


class FramesBatchRequest(BaseModel):
    frames: Annotated[list[Frame], Field(max_length=500, min_length=1)]
