# generated by datamodel-codegen:
#   filename:  processing/frames_batch.response.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class Result(BaseModel):
    sha256: Annotated[
        str,
        Field(
            description="Lower-case hex SHA-256 of a file's bytes. The natural key of a frame everywhere.",
            pattern="^[0-9a-f]{64}$",
        ),
    ]
    status: Literal["ok", "error"]
    id: int | None = None
    target_id: int | None = None
    exposure_plan_id: int | None = None
    error: str | None = None


class FramesBatchResponse(BaseModel):
    results: list[Result]
