# generated by datamodel-codegen:
#   filename:  processing/frames_patch.request.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field

from ..shared import common


class Frame(BaseModel):
    sha256: Annotated[
        str,
        Field(
            description="Lower-case hex SHA-256 of a file's bytes. The natural key of a frame everywhere.",
            pattern="^[0-9a-f]{64}$",
        ),
    ]
    status: Literal["collected", "valid", "invalid", "held", "processed", "rejected"] | None = (
        None
    )
    status_reason: str | None = None
    quality: common.FrameQuality | None = None
    storage: common.FrameStorage | None = None


class FramesPatchRequest(BaseModel):
    frames: Annotated[list[Frame], Field(max_length=500, min_length=1)]
