# generated by datamodel-codegen:
#   filename:  processing/issue.request.json

from __future__ import annotations

from datetime import date
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field


class IssueRequest(BaseModel):
    altair_id: int | None = None
    kind: Annotated[
        str,
        Field(
            description="Altair issue kind, e.g. PROJECT_UNRESOLVED, HUB_CONFIG_MISMATCH, STALE_REFERENCE (SPEC §10.1).",
            pattern="^[A-Z][A-Z0-9_]*$",
        ),
    ]
    severity: Literal["blocking", "warning", "info"]
    status: Literal["open", "resolved", "waived"]
    message: str
    requirement: Annotated[
        dict[str, Any] | None,
        Field(description="What must be true for the issue to resolve itself."),
    ] = None
    scope: Annotated[
        dict[str, Any] | None,
        Field(
            description="Altair's issue scope (rig, project, night, filter, hub_target_id...)."
        ),
    ] = None
    optical_train: str | None = None
    target_id: int | None = None
    night: date | None = None
    filter: str | None = None
    resolution: str | None = None
