# generated by datamodel-codegen:
#   filename:  processing/job.request.json

from __future__ import annotations

from datetime import date
from typing import Literal

from pydantic import AwareDatetime, BaseModel


class JobRequest(BaseModel):
    kind: Literal["CALIB_MASTER", "NIGHT_STACK", "PROJECT_REFERENCE", "MERGE"]
    status: Literal["queued", "staging", "waiting_data", "running", "succeeded", "failed", "skipped", "blocked"]
    target_id: int | None = None
    night: date | None = None
    filter: str | None = None
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None
    error: str | None = None
