# generated by datamodel-codegen:
#   filename:  processing/night.request.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, Field

from ..shared import common


class NightRequest(BaseModel):
    state: Literal["open", "closing", "closed"]
    closed_by: Annotated[
        Literal["session_end_marker", "session_end", "quiescence", "scheduled", "manual"] | None,
        Field(
            description="What closed the night: the SPEC v0.7 values, plus session_end for a night_ready command from the Hub (queued by the rig agent's session_end)."
        ),
    ] = None
    session_end_at: AwareDatetime | None = None
    lights_count: Annotated[int | None, Field(ge=0)] = None
    calibration_count: Annotated[int | None, Field(ge=0)] = None
    light_seconds: Annotated[float | None, Field(ge=0.0)] = None
    manifest_sha256: common.Sha256 | None = None
