# generated by datamodel-codegen:
#   filename:  processing/night_digest.response.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field
from typing_extensions import TypeAliasType

ByTypeAdditionalProperty = TypeAliasType(
    "ByTypeAdditionalProperty", Annotated[int, Field(ge=0)]
)


class NightDigestResponse(BaseModel):
    frame_count: Annotated[int, Field(ge=0)]
    sha256_xor: Annotated[
        str,
        Field(
            description="Lower-case hex SHA-256 of a file's bytes. The natural key of a frame everywhere.",
            pattern="^[0-9a-f]{64}$",
        ),
    ]
    by_type: dict[Literal["light", "dark", "flat", "bias", "darkflat"], ByTypeAdditionalProperty]
