# generated by datamodel-codegen:
#   filename:  shared/common.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class Common(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Definitions shared by the worker and processing contracts (SYSTEM_ARCHITECTURE.md §4 and §5).",
            title="Common",
        ),
    ]


class Sha256(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Lower-case hex SHA-256 of a file's bytes. The natural key of a frame everywhere.",
            pattern="^[0-9a-f]{64}$",
        ),
    ]


class FrameStorage(BaseModel):
    nas: bool | None = None
    s3: Literal["STANDARD_IA", "DEEP_ARCHIVE"] | None = None
    verified_at: AwareDatetime | None = None


class FrameQuality(BaseModel):
    fwhm: float | None = None
    eccentricity: float | None = None
    stars: int | None = None
    psf_signal_weight: float | None = None
    weight: float | None = None


class MultiNightSettings(BaseModel):
    enabled: bool | None = None
    mode: Literal["master_merge", "frame_reintegration"] | None = None


class ProcessingSettings(BaseModel):
    multi_night: MultiNightSettings | None = None
    reference_filter: str | None = None
    drizzle_scale: Annotated[int | None, Field(ge=1)] = None
    keep_calibrated_frames: bool | None = None
    pin_to_nas: bool | None = None
    min_lights_per_stack: Annotated[int | None, Field(ge=1)] = None
    max_fwhm_ratio_to_project_median: Annotated[float | None, Field(gt=0.0)] = None
    wbpp_profile: str | None = None


class DataProductKind(
    RootModel[Literal["night_master", "multi_night_master", "project_reference", "provisional_noflat"]]
):
    root: Annotated[
        Literal["night_master", "multi_night_master", "project_reference", "provisional_noflat"],
        Field(
            description="Kinds Altair reports. Legacy worker uploads (sub, stacked, preview, log) use POST /targets/:id/files."
        ),
    ]
