# generated by datamodel-codegen:
#   filename:  shared/error.response.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class ErrorResponse(BaseModel):
    error: str
    details: dict[str, Any] | None = None
