# generated by datamodel-codegen:
#   filename:  shared/heartbeat.request.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field


class HeartbeatRequest(BaseModel):
    agent: Literal["robs", "altair"]
    version: str
    api_revision: Annotated[
        int | None,
        Field(description="The newest api_revision the client understands.", ge=1),
    ] = None
    status: Annotated[
        dict[str, Any],
        Field(
            description="Free-form agent status. Altair sends versions, queue depth, running job, locations reachable, NAS free %, S3 backlog and outbox depth."
        ),
    ]
